--
-- ISO 4217 - Country Data
--

INSERT INTO countries VALUES(248,'AALAND ISLANDS                                  ','AX','ALA');
INSERT INTO countries VALUES(004,'AFGHANISTAN                                     ','AF','AFG');
INSERT INTO countries VALUES(008,'ALBANIA                                         ','AL','ALB');
INSERT INTO countries VALUES(012,'ALGERIA                                         ','DZ','DZA');
INSERT INTO countries VALUES(016,'AMERICAN SAMOA                                  ','AS','ASM');
INSERT INTO countries VALUES(020,'ANDORRA                                         ','AD','AND');
INSERT INTO countries VALUES(024,'ANGOLA                                          ','AO','AGO');
INSERT INTO countries VALUES(660,'ANGUILLA                                        ','AI','AIA');
INSERT INTO countries VALUES(010,'ANTARCTICA                                      ','AQ','ATA');
INSERT INTO countries VALUES(028,'ANTIGUA AND BARBUDA                             ','AG','ATG');
INSERT INTO countries VALUES(032,'ARGENTINA                                       ','AR','ARG');
INSERT INTO countries VALUES(051,'ARMENIA                                         ','AM','ARM');
INSERT INTO countries VALUES(533,'ARUBA                                           ','AW','ABW');
INSERT INTO countries VALUES(036,'AUSTRALIA                                       ','AU','AUS');
INSERT INTO countries VALUES(040,'AUSTRIA                                         ','AT','AUT');
INSERT INTO countries VALUES(031,'AZERBAIJAN                                      ','AZ','AZE');
INSERT INTO countries VALUES(044,'BAHAMAS                                         ','BS','BHS');
INSERT INTO countries VALUES(048,'BAHRAIN                                         ','BH','BHR');
INSERT INTO countries VALUES(050,'BANGLADESH                                      ','BD','BGD');
INSERT INTO countries VALUES(052,'BARBADOS                                        ','BB','BRB');
INSERT INTO countries VALUES(112,'BELARUS                                         ','BY','BLR');
INSERT INTO countries VALUES(056,'BELGIUM                                         ','BE','BEL');
INSERT INTO countries VALUES(084,'BELIZE                                          ','BZ','BLZ');
INSERT INTO countries VALUES(204,'BENIN                                           ','BJ','BEN');
INSERT INTO countries VALUES(060,'BERMUDA                                         ','BM','BMU');
INSERT INTO countries VALUES(064,'BHUTAN                                          ','BT','BTN');
INSERT INTO countries VALUES(068,'BOLIVIA                                         ','BO','BOL');
INSERT INTO countries VALUES(070,'BOSNIA AND HERZEGOWINA                          ','BA','BIH');
INSERT INTO countries VALUES(072,'BOTSWANA                                        ','BW','BWA');
INSERT INTO countries VALUES(074,'BOUVET ISLAND                                   ','BV','BVT');
INSERT INTO countries VALUES(076,'BRAZIL                                          ','BR','BRA');
INSERT INTO countries VALUES(086,'BRITISH INDIAN OCEAN TERRITORY                  ','IO','IOT');
INSERT INTO countries VALUES(096,'BRUNEI DARUSSALAM                               ','BN','BRN');
INSERT INTO countries VALUES(100,'BULGARIA                                        ','BG','BGR');
INSERT INTO countries VALUES(854,'BURKINA FASO                                    ','BF','BFA');
INSERT INTO countries VALUES(108,'BURUNDI                                         ','BI','BDI');
INSERT INTO countries VALUES(116,'CAMBODIA                                        ','KH','KHM');
INSERT INTO countries VALUES(120,'CAMEROON                                        ','CM','CMR');
INSERT INTO countries VALUES(124,'CANADA                                          ','CA','CAN');
INSERT INTO countries VALUES(132,'CAPE VERDE                                      ','CV','CPV');
INSERT INTO countries VALUES(136,'CAYMAN ISLANDS                                  ','KY','CYM');
INSERT INTO countries VALUES(140,'CENTRAL AFRICAN REPUBLIC                        ','CF','CAF');
INSERT INTO countries VALUES(148,'CHAD                                            ','TD','TCD');
INSERT INTO countries VALUES(152,'CHILE                                           ','CL','CHL');
INSERT INTO countries VALUES(156,'CHINA                                           ','CN','CHN');
INSERT INTO countries VALUES(162,'CHRISTMAS ISLAND                                ','CX','CXR');
INSERT INTO countries VALUES(166,'COCOS (KEELING) ISLANDS                         ','CC','CCK');
INSERT INTO countries VALUES(170,'COLOMBIA                                        ','CO','COL');
INSERT INTO countries VALUES(174,'COMOROS                                         ','KM','COM');
INSERT INTO countries VALUES(180,'CONGO, Democratic Republic of (was Zaire)       ','CD','COD');
INSERT INTO countries VALUES(178,'CONGO, Republic of                              ','CG','COG');
INSERT INTO countries VALUES(184,'COOK ISLANDS                                    ','CK','COK');
INSERT INTO countries VALUES(188,'COSTA RICA                                      ','CR','CRI');
INSERT INTO countries VALUES(384,'COTE D''IVOIRE                                  ','CI','CIV');
INSERT INTO countries VALUES(191,'CROATIA (local name: Hrvatska)                  ','HR','HRV'); 
INSERT INTO countries VALUES(192,'CUBA                                            ','CU','CUB');
INSERT INTO countries VALUES(196,'CYPRUS                                          ','CY','CYP');
INSERT INTO countries VALUES(203,'CZECH REPUBLIC                                  ','CZ','CZE');
INSERT INTO countries VALUES(208,'DENMARK                                         ','DK','DNK');
INSERT INTO countries VALUES(262,'DJIBOUTI                                        ','DJ','DJI');
INSERT INTO countries VALUES(212,'DOMINICA                                        ','DM','DMA');
INSERT INTO countries VALUES(214,'DOMINICAN REPUBLIC                              ','DO','DOM');
INSERT INTO countries VALUES(218,'ECUADOR                                         ','EC','ECU');
INSERT INTO countries VALUES(818,'EGYPT                                           ','EG','EGY');
INSERT INTO countries VALUES(222,'EL SALVADOR                                     ','SV','SLV');
INSERT INTO countries VALUES(226,'EQUATORIAL GUINEA                               ','GQ','GNQ');
INSERT INTO countries VALUES(232,'ERITREA                                         ','ER','ERI');
INSERT INTO countries VALUES(233,'ESTONIA                                         ','EE','EST');
INSERT INTO countries VALUES(231,'ETHIOPIA                                        ','ET','ETH');
INSERT INTO countries VALUES(238,'FALKLAND ISLANDS (MALVINAS)                     ','FK','FLK');
INSERT INTO countries VALUES(234,'FAROE ISLANDS                                   ','FO','FRO');
INSERT INTO countries VALUES(242,'FIJI                                            ','FJ','FJI');
INSERT INTO countries VALUES(246,'FINLAND                                         ','FI','FIN');
INSERT INTO countries VALUES(250,'FRANCE                                          ','FR','FRA');
INSERT INTO countries VALUES(254,'FRENCH GUIANA                                   ','GF','GUF');
INSERT INTO countries VALUES(258,'FRENCH POLYNESIA                                ','PF','PYF');
INSERT INTO countries VALUES(260,'FRENCH SOUTHERN TERRITORIES                     ','TF','ATF');
INSERT INTO countries VALUES(266,'GABON                                           ','GA','GAB');
INSERT INTO countries VALUES(270,'GAMBIA                                          ','GM','GMB');
INSERT INTO countries VALUES(268,'GEORGIA                                         ','GE','GEO');
INSERT INTO countries VALUES(276,'GERMANY                                         ','DE','DEU');
INSERT INTO countries VALUES(288,'GHANA                                           ','GH','GHA');
INSERT INTO countries VALUES(292,'GIBRALTAR                                       ','GI','GIB');
INSERT INTO countries VALUES(300,'GREECE                                          ','GR','GRC');
INSERT INTO countries VALUES(304,'GREENLAND                                       ','GL','GRL');
INSERT INTO countries VALUES(308,'GRENADA                                         ','GD','GRD');
INSERT INTO countries VALUES(312,'GUADELOUPE                                      ','GP','GLP');
INSERT INTO countries VALUES(316,'GUAM                                            ','GU','GUM');
INSERT INTO countries VALUES(320,'GUATEMALA                                       ','GT','GTM');
INSERT INTO countries VALUES(324,'GUINEA                                          ','GN','GIN');
INSERT INTO countries VALUES(624,'GUINEA-BISSAU                                   ','GW','GNB');
INSERT INTO countries VALUES(328,'GUYANA                                          ','GY','GUY');
INSERT INTO countries VALUES(332,'HAITI                                           ','HT','HTI');
INSERT INTO countries VALUES(334,'HEARD AND MC DONALD ISLANDS                     ','HM','HMD');
INSERT INTO countries VALUES(340,'HONDURAS                                        ','HN','HND');
INSERT INTO countries VALUES(344,'HONG KONG                                       ','HK','HKG');
INSERT INTO countries VALUES(348,'HUNGARY                                         ','HU','HUN');
INSERT INTO countries VALUES(352,'ICELAND                                         ','IS','ISL');
INSERT INTO countries VALUES(356,'INDIA                                           ','IN','IND');
INSERT INTO countries VALUES(360,'INDONESIA                                       ','ID','IDN');
INSERT INTO countries VALUES(364,'IRAN (ISLAMIC REPUBLIC OF)                      ','IR','IRN');
INSERT INTO countries VALUES(368,'IRAQ                                            ','IQ','IRQ');
INSERT INTO countries VALUES(372,'IRELAND                                         ','IE','IRL');
INSERT INTO countries VALUES(376,'ISRAEL                                          ','IL','ISR');
INSERT INTO countries VALUES(380,'ITALY                                           ','IT','ITA');
INSERT INTO countries VALUES(388,'JAMAICA                                         ','JM','JAM');
INSERT INTO countries VALUES(392,'JAPAN                                           ','JP','JPN');
INSERT INTO countries VALUES(400,'JORDAN                                          ','JO','JOR');
INSERT INTO countries VALUES(398,'KAZAKHSTAN                                      ','KZ','KAZ');
INSERT INTO countries VALUES(404,'KENYA                                           ','KE','KEN');
INSERT INTO countries VALUES(296,'KIRIBATI                                        ','KI','KIR');
INSERT INTO countries VALUES(408,'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF         ','KP','PRK');
INSERT INTO countries VALUES(410,'KOREA, REPUBLIC OF                              ','KR','KOR');
INSERT INTO countries VALUES(414,'KUWAIT                                          ','KW','KWT');
INSERT INTO countries VALUES(417,'KYRGYZSTAN                                      ','KG','KGZ');
INSERT INTO countries VALUES(418,'LAO PEOPLE''S DEMOCRATIC REPUBLIC               ','LA','LAO');
INSERT INTO countries VALUES(428,'LATVIA                                          ','LV','LVA');
INSERT INTO countries VALUES(422,'LEBANON                                         ','LB','LBN');
INSERT INTO countries VALUES(426,'LESOTHO                                         ','LS','LSO');
INSERT INTO countries VALUES(430,'LIBERIA                                         ','LR','LBR');
INSERT INTO countries VALUES(434,'LIBYAN ARAB JAMAHIRIYA                          ','LY','LBY');
INSERT INTO countries VALUES(438,'LIECHTENSTEIN                                   ','LI','LIE');
INSERT INTO countries VALUES(440,'LITHUANIA                                       ','LT','LTU');
INSERT INTO countries VALUES(442,'LUXEMBOURG                                      ','LU','LUX');
INSERT INTO countries VALUES(446,'MACAU                                           ','MO','MAC');
INSERT INTO countries VALUES(807,'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF      ','MK','MKD');
INSERT INTO countries VALUES(450,'MADAGASCAR                                      ','MG','MDG');
INSERT INTO countries VALUES(454,'MALAWI                                          ','MW','MWI');
INSERT INTO countries VALUES(458,'MALAYSIA                                        ','MY','MYS');
INSERT INTO countries VALUES(462,'MALDIVES                                        ','MV','MDV');
INSERT INTO countries VALUES(466,'MALI                                            ','ML','MLI');
INSERT INTO countries VALUES(470,'MALTA                                           ','MT','MLT');
INSERT INTO countries VALUES(584,'MARSHALL ISLANDS                                ','MH','MHL');
INSERT INTO countries VALUES(474,'MARTINIQUE                                      ','MQ','MTQ');
INSERT INTO countries VALUES(478,'MAURITANIA                                      ','MR','MRT');
INSERT INTO countries VALUES(480,'MAURITIUS                                       ','MU','MUS');
INSERT INTO countries VALUES(175,'MAYOTTE                                         ','YT','MYT');
INSERT INTO countries VALUES(484,'MEXICO                                          ','MX','MEX');
INSERT INTO countries VALUES(583,'MICRONESIA, FEDERATED STATES OF                 ','FM','FSM');
INSERT INTO countries VALUES(498,'MOLDOVA, REPUBLIC OF                            ','MD','MDA');
INSERT INTO countries VALUES(492,'MONACO                                          ','MC','MCO');
INSERT INTO countries VALUES(496,'MONGOLIA                                        ','MN','MNG');
INSERT INTO countries VALUES(500,'MONTSERRAT                                      ','MS','MSR');
INSERT INTO countries VALUES(504,'MOROCCO                                         ','MA','MAR');
INSERT INTO countries VALUES(508,'MOZAMBIQUE                                      ','MZ','MOZ');
INSERT INTO countries VALUES(104,'MYANMAR                                         ','MM','MMR');
INSERT INTO countries VALUES(516,'NAMIBIA                                         ','NA','NAM');
INSERT INTO countries VALUES(520,'NAURU                                           ','NR','NRU');
INSERT INTO countries VALUES(524,'NEPAL                                           ','NP','NPL');
INSERT INTO countries VALUES(528,'NETHERLANDS                                     ','NL','NLD');
INSERT INTO countries VALUES(530,'NETHERLANDS ANTILLES                            ','AN','ANT');
INSERT INTO countries VALUES(540,'NEW CALEDONIA                                   ','NC','NCL');
INSERT INTO countries VALUES(554,'NEW ZEALAND                                     ','NZ','NZL');
INSERT INTO countries VALUES(558,'NICARAGUA                                       ','NI','NIC');
INSERT INTO countries VALUES(562,'NIGER                                           ','NE','NER');
INSERT INTO countries VALUES(566,'NIGERIA                                         ','NG','NGA');
INSERT INTO countries VALUES(570,'NIUE                                            ','NU','NIU');
INSERT INTO countries VALUES(574,'NORFOLK ISLAND                                  ','NF','NFK');
INSERT INTO countries VALUES(580,'NORTHERN MARIANA ISLANDS                        ','MP','MNP');
INSERT INTO countries VALUES(578,'NORWAY                                          ','NO','NOR');
INSERT INTO countries VALUES(512,'OMAN                                            ','OM','OMN');
INSERT INTO countries VALUES(586,'PAKISTAN                                        ','PK','PAK');
INSERT INTO countries VALUES(585,'PALAU                                           ','PW','PLW');
INSERT INTO countries VALUES(275,'PALESTINIAN TERRITORY, Occupied                 ','PS','PSE');
INSERT INTO countries VALUES(591,'PANAMA                                          ','PA','PAN');
INSERT INTO countries VALUES(598,'PAPUA NEW GUINEA                                ','PG','PNG');
INSERT INTO countries VALUES(600,'PARAGUAY                                        ','PY','PRY');
INSERT INTO countries VALUES(604,'PERU                                            ','PE','PER');
INSERT INTO countries VALUES(608,'PHILIPPINES                                     ','PH','PHL');
INSERT INTO countries VALUES(612,'PITCAIRN                                        ','PN','PCN');
INSERT INTO countries VALUES(616,'POLAND                                          ','PL','POL');
INSERT INTO countries VALUES(620,'PORTUGAL                                        ','PT','PRT');
INSERT INTO countries VALUES(630,'PUERTO RICO                                     ','PR','PRI');
INSERT INTO countries VALUES(634,'QATAR                                           ','QA','QAT');
INSERT INTO countries VALUES(638,'REUNION                                         ','RE','REU');
INSERT INTO countries VALUES(642,'ROMANIA                                         ','RO','ROU');
INSERT INTO countries VALUES(643,'RUSSIAN FEDERATION                              ','RU','RUS');
INSERT INTO countries VALUES(646,'RWANDA                                          ','RW','RWA');
INSERT INTO countries VALUES(654,'SAINT HELENA                                    ','SH','SHN');
INSERT INTO countries VALUES(659,'SAINT KITTS AND NEVIS                           ','KN','KNA');
INSERT INTO countries VALUES(662,'SAINT LUCIA                                     ','LC','LCA');
INSERT INTO countries VALUES(666,'SAINT PIERRE AND MIQUELON                       ','PM','SPM');
INSERT INTO countries VALUES(670,'SAINT VINCENT AND THE GRENADINES                ','VC','VCT');
INSERT INTO countries VALUES(882,'SAMOA                                           ','WS','WSM');
INSERT INTO countries VALUES(674,'SAN MARINO                                      ','SM','SMR');
INSERT INTO countries VALUES(678,'SAO TOME AND PRINCIPE                           ','ST','STP');
INSERT INTO countries VALUES(682,'SAUDI ARABIA                                    ','SA','SAU');
INSERT INTO countries VALUES(686,'SENEGAL                                         ','SN','SEN');
INSERT INTO countries VALUES(891,'SERBIA AND MONTENEGRO                           ','CS','SCG');
INSERT INTO countries VALUES(690,'SEYCHELLES                                      ','SC','SYC');
INSERT INTO countries VALUES(694,'SIERRA LEONE                                    ','SL','SLE');
INSERT INTO countries VALUES(702,'SINGAPORE                                       ','SG','SGP');
INSERT INTO countries VALUES(703,'SLOVAKIA                                        ','SK','SVK');
INSERT INTO countries VALUES(705,'SLOVENIA                                        ','SI','SVN');
INSERT INTO countries VALUES(090,'SOLOMON ISLANDS                                 ','SB','SLB');
INSERT INTO countries VALUES(706,'SOMALIA                                         ','SO','SOM');
INSERT INTO countries VALUES(710,'SOUTH AFRICA                                    ','ZA','ZAF');
INSERT INTO countries VALUES(239,'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS    ','GS','SGS');
INSERT INTO countries VALUES(724,'SPAIN                                           ','ES','ESP');
INSERT INTO countries VALUES(144,'SRI LANKA                                       ','LK','LKA');
INSERT INTO countries VALUES(736,'SUDAN                                           ','SD','SDN');
INSERT INTO countries VALUES(740,'SURINAME                                        ','SR','SUR');
INSERT INTO countries VALUES(744,'SVALBARD AND JAN MAYEN ISLANDS                  ','SJ','SJM');
INSERT INTO countries VALUES(748,'SWAZILAND                                       ','SZ','SWZ');
INSERT INTO countries VALUES(752,'SWEDEN                                          ','SE','SWE');
INSERT INTO countries VALUES(756,'SWITZERLAND                                     ','CH','CHE');
INSERT INTO countries VALUES(760,'SYRIAN ARAB REPUBLIC                            ','SY','SYR');
INSERT INTO countries VALUES(158,'TAIWAN                                          ','TW','TWN');
INSERT INTO countries VALUES(762,'TAJIKISTAN                                      ','TJ','TJK');
INSERT INTO countries VALUES(834,'TANZANIA, UNITED REPUBLIC OF                    ','TZ','TZA');
INSERT INTO countries VALUES(764,'THAILAND                                        ','TH','THA');
INSERT INTO countries VALUES(626,'TIMOR-LESTE                                     ','TL','TLS');
INSERT INTO countries VALUES(768,'TOGO                                            ','TG','TGO');
INSERT INTO countries VALUES(772,'TOKELAU                                         ','TK','TKL');
INSERT INTO countries VALUES(776,'TONGA                                           ','TO','TON');
INSERT INTO countries VALUES(780,'TRINIDAD AND TOBAGO                             ','TT','TTO');
INSERT INTO countries VALUES(788,'TUNISIA                                         ','TN','TUN');
INSERT INTO countries VALUES(792,'TURKEY                                          ','TR','TUR');
INSERT INTO countries VALUES(795,'TURKMENISTAN                                    ','TM','TKM');
INSERT INTO countries VALUES(796,'TURKS AND CAICOS ISLANDS                        ','TC','TCA');
INSERT INTO countries VALUES(798,'TUVALU                                          ','TV','TUV');
INSERT INTO countries VALUES(800,'UGANDA                                          ','UG','UGA');
INSERT INTO countries VALUES(804,'UKRAINE                                         ','UA','UKR');
INSERT INTO countries VALUES(784,'UNITED ARAB EMIRATES                            ','AE','ARE');
INSERT INTO countries VALUES(826,'UNITED KINGDOM                                  ','GB','GBR');
INSERT INTO countries VALUES(840,'UNITED STATES                                   ','US','USA');
INSERT INTO countries VALUES(581,'UNITED STATES MINOR OUTLYING ISLANDS            ','UM','UMI');
INSERT INTO countries VALUES(858,'URUGUAY                                         ','UY','URY');
INSERT INTO countries VALUES(860,'UZBEKISTAN                                      ','UZ','UZB');
INSERT INTO countries VALUES(548,'VANUATU                                         ','VU','VUT');
INSERT INTO countries VALUES(336,'VATICAN CITY STATE (HOLY SEE)                   ','VA','VAT');
INSERT INTO countries VALUES(862,'VENEZUELA                                       ','VE','VEN');
INSERT INTO countries VALUES(704,'VIET NAM                                        ','VN','VNM');
INSERT INTO countries VALUES(092,'VIRGIN ISLANDS (BRITISH)                        ','VG','VGB');
INSERT INTO countries VALUES(850,'VIRGIN ISLANDS (U.S.)                           ','VI','VIR');
INSERT INTO countries VALUES(876,'WALLIS AND FUTUNA ISLANDS                       ','WF','WLF');
INSERT INTO countries VALUES(732,'WESTERN SAHARA                                  ','EH','ESH');
INSERT INTO countries VALUES(887,'YEMEN                                           ','YE','YEM');
INSERT INTO countries VALUES(894,'ZAMBIA                                          ','ZM','ZMB');
INSERT INTO countries VALUES(716,'ZIMBABWE                                        ','ZW','ZWE');
