--
-- ISO 4217 - Country Codes Data
--

INSERT INTO currencies (`code`,`money_name`) VALUES('AED','United Arab Emirates Dirham');
INSERT INTO currencies (`code`,`money_name`) VALUES('AFN','Afghanistan Afghani');
INSERT INTO currencies (`code`,`money_name`) VALUES('ALL','Albania Lek');
INSERT INTO currencies (`code`,`money_name`) VALUES('AMD','Armenia Dram');
INSERT INTO currencies (`code`,`money_name`) VALUES('ANG','Netherlands Antilles Guilder');
INSERT INTO currencies (`code`,`money_name`) VALUES('AOA','Angola Kwanza');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('ARS','Argentina Peso','$');
INSERT INTO currencies (`code`,`money_name`) VALUES('AUD','Australia Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('AWG','Aruba Guilder');
INSERT INTO currencies (`code`,`money_name`) VALUES('AZN','Azerbaijan New Manat');
INSERT INTO currencies (`code`,`money_name`) VALUES('BAM','Bosnia and Herzegovina Convertible Marka');
INSERT INTO currencies (`code`,`money_name`) VALUES('BBD','Barbados Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('BDT','Bangladesh Taka');
INSERT INTO currencies (`code`,`money_name`) VALUES('BGN','Bulgaria Lev');
INSERT INTO currencies (`code`,`money_name`) VALUES('BHD','Bahrain Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('BIF','Burundi Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('BMD','Bermuda Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('BND','Brunei Darussalam Dollar');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('BOB','Bolivia Boliviano','Bs.');
INSERT INTO currencies (`code`,`money_name`) VALUES('BRL','Brazil Real');
INSERT INTO currencies (`code`,`money_name`) VALUES('BSD','Bahamas Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('BTN','Bhutan Ngultrum');
INSERT INTO currencies (`code`,`money_name`) VALUES('BWP','Botswana Pula');
INSERT INTO currencies (`code`,`money_name`) VALUES('BYR','Belarus Ruble');
INSERT INTO currencies (`code`,`money_name`) VALUES('BZD','Belize Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('CAD','Canada Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('CDF','Congo/Kinshasa Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('CHF','Switzerland Franc');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('CLP','Chile Peso','$');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('CNY','China Yuan Renminbi','¥');
INSERT INTO currencies (`code`,`money_name`) VALUES('COP','Colombia Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('CRC','Costa Rica Colon');
INSERT INTO currencies (`code`,`money_name`) VALUES('CUC','Cuba Convertible Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('CUP','Cuba Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('CVE','Cape Verde Escudo');
INSERT INTO currencies (`code`,`money_name`) VALUES('CZK','Czech Republic Koruna');
INSERT INTO currencies (`code`,`money_name`) VALUES('DJF','Djibouti Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('DKK','Denmark Krone');
INSERT INTO currencies (`code`,`money_name`) VALUES('DOP','Dominican Republic Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('DZD','Algeria Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('EGP','Egypt Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('ERN','Eritrea Nakfa');
INSERT INTO currencies (`code`,`money_name`) VALUES('ETB','Ethiopia Birr');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('EUR','Euro Member Countries','€');
INSERT INTO currencies (`code`,`money_name`) VALUES('FJD','Fiji Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('FKP','Falkland Islands (Malvinas) Pound');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('GBP','United Kingdom Pound','£');
INSERT INTO currencies (`code`,`money_name`) VALUES('GEL','Georgia Lari');
INSERT INTO currencies (`code`,`money_name`) VALUES('GGP','Guernsey Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('GHS','Ghana Cedi');
INSERT INTO currencies (`code`,`money_name`) VALUES('GIP','Gibraltar Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('GMD','Gambia Dalasi');
INSERT INTO currencies (`code`,`money_name`) VALUES('GNF','Guinea Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('GTQ','Guatemala Quetzal');
INSERT INTO currencies (`code`,`money_name`) VALUES('GYD','Guyana Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('HKD','Hong Kong Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('HNL','Honduras Lempira');
INSERT INTO currencies (`code`,`money_name`) VALUES('HRK','Croatia Kuna');
INSERT INTO currencies (`code`,`money_name`) VALUES('HTG','Haiti Gourde');
INSERT INTO currencies (`code`,`money_name`) VALUES('HUF','Hungary Forint');
INSERT INTO currencies (`code`,`money_name`) VALUES('IDR','Indonesia Rupiah');
INSERT INTO currencies (`code`,`money_name`) VALUES('ILS','Israel Shekel');
INSERT INTO currencies (`code`,`money_name`) VALUES('IMP','Isle of Man Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('INR','India Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('IQD','Iraq Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('IRR','Iran Rial');
INSERT INTO currencies (`code`,`money_name`) VALUES('ISK','Iceland Krona');
INSERT INTO currencies (`code`,`money_name`) VALUES('JEP','Jersey Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('JMD','Jamaica Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('JOD','Jordan Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('JPY','Japan Yen');
INSERT INTO currencies (`code`,`money_name`) VALUES('KES','Kenya Shilling');
INSERT INTO currencies (`code`,`money_name`) VALUES('KGS','Kyrgyzstan Som');
INSERT INTO currencies (`code`,`money_name`) VALUES('KHR','Cambodia Riel');
INSERT INTO currencies (`code`,`money_name`) VALUES('KMF','Comoros Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('KPW','Korea (North) Won');
INSERT INTO currencies (`code`,`money_name`) VALUES('KRW','Korea (South) Won');
INSERT INTO currencies (`code`,`money_name`) VALUES('KWD','Kuwait Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('KYD','Cayman Islands Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('KZT','Kazakhstan Tenge');
INSERT INTO currencies (`code`,`money_name`) VALUES('LAK','Laos Kip');
INSERT INTO currencies (`code`,`money_name`) VALUES('LBP','Lebanon Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('LKR','Sri Lanka Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('LRD','Liberia Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('LSL','Lesotho Loti');
INSERT INTO currencies (`code`,`money_name`) VALUES('LTL','Lithuania Litas');
INSERT INTO currencies (`code`,`money_name`) VALUES('LVL','Latvia Lat');
INSERT INTO currencies (`code`,`money_name`) VALUES('LYD','Libya Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('MAD','Morocco Dirham');
INSERT INTO currencies (`code`,`money_name`) VALUES('MDL','Moldova Leu');
INSERT INTO currencies (`code`,`money_name`) VALUES('MGA','Madagascar Ariary');
INSERT INTO currencies (`code`,`money_name`) VALUES('MKD','Macedonia Denar');
INSERT INTO currencies (`code`,`money_name`) VALUES('MMK','Myanmar (Burma) Kyat');
INSERT INTO currencies (`code`,`money_name`) VALUES('MNT','Mongolia Tughrik');
INSERT INTO currencies (`code`,`money_name`) VALUES('MOP','Macau Pataca');
INSERT INTO currencies (`code`,`money_name`) VALUES('MRO','Mauritania Ouguiya');
INSERT INTO currencies (`code`,`money_name`) VALUES('MUR','Mauritius Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('MVR','Maldives (Maldive Islands) Rufiyaa');
INSERT INTO currencies (`code`,`money_name`) VALUES('MWK','Malawi Kwacha');
INSERT INTO currencies (`code`,`money_name`) VALUES('MXN','Mexico Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('MYR','Malaysia Ringgit');
INSERT INTO currencies (`code`,`money_name`) VALUES('MZN','Mozambique Metical');
INSERT INTO currencies (`code`,`money_name`) VALUES('NAD','Namibia Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('NGN','Nigeria Naira');
INSERT INTO currencies (`code`,`money_name`) VALUES('NIO','Nicaragua Cordoba');
INSERT INTO currencies (`code`,`money_name`) VALUES('NOK','Norway Krone');
INSERT INTO currencies (`code`,`money_name`) VALUES('NPR','Nepal Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('NZD','New Zealand Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('OMR','Oman Rial');
INSERT INTO currencies (`code`,`money_name`) VALUES('PAB','Panama Balboa');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('PEN','Peru Nuevo Sol','S/.');
INSERT INTO currencies (`code`,`money_name`) VALUES('PGK','Papua New Guinea Kina');
INSERT INTO currencies (`code`,`money_name`) VALUES('PHP','Philippines Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('PKR','Pakistan Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('PLN','Poland Zloty');
INSERT INTO currencies (`code`,`money_name`) VALUES('PYG','Paraguay Guarani');
INSERT INTO currencies (`code`,`money_name`) VALUES('QAR','Qatar Riyal');
INSERT INTO currencies (`code`,`money_name`) VALUES('RON','Romania New Leu');
INSERT INTO currencies (`code`,`money_name`) VALUES('RSD','Serbia Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('RUB','Russia Ruble');
INSERT INTO currencies (`code`,`money_name`) VALUES('RWF','Rwanda Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('SAR','Saudi Arabia Riyal');
INSERT INTO currencies (`code`,`money_name`) VALUES('SBD','Solomon Islands Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('SCR','Seychelles Rupee');
INSERT INTO currencies (`code`,`money_name`) VALUES('SDG','Sudan Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('SEK','Sweden Krona');
INSERT INTO currencies (`code`,`money_name`) VALUES('SGD','Singapore Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('SHP','Saint Helena Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('SLL','Sierra Leone Leone');
INSERT INTO currencies (`code`,`money_name`) VALUES('SOS','Somalia Shilling');
INSERT INTO currencies (`code`,`money_name`) VALUES('SPL','	Seborga Luigino');
INSERT INTO currencies (`code`,`money_name`) VALUES('SRD','Suriname Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('STD','São Tomé and Príncipe Dobra');
INSERT INTO currencies (`code`,`money_name`) VALUES('SVC','El Salvador Colon');
INSERT INTO currencies (`code`,`money_name`) VALUES('SYP','Syria Pound');
INSERT INTO currencies (`code`,`money_name`) VALUES('SZL','Swaziland Lilangeni');
INSERT INTO currencies (`code`,`money_name`) VALUES('THB','Thailand Baht');
INSERT INTO currencies (`code`,`money_name`) VALUES('TJS','Tajikistan Somoni');
INSERT INTO currencies (`code`,`money_name`) VALUES('TMT','Turkmenistan Manat');
INSERT INTO currencies (`code`,`money_name`) VALUES('TND','Tunisia Dinar');
INSERT INTO currencies (`code`,`money_name`) VALUES('TOP','Tonga Pa''anga');
INSERT INTO currencies (`code`,`money_name`) VALUES('TRY','Turkey Lira');
INSERT INTO currencies (`code`,`money_name`) VALUES('TTD','Trinidad and Tobago Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('TVD','Tuvalu Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('TWD','Taiwan New Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('TZS','Tanzania Shilling');
INSERT INTO currencies (`code`,`money_name`) VALUES('UAH','Ukraine Hryvna');
INSERT INTO currencies (`code`,`money_name`) VALUES('UGX','Uganda Shilling');
INSERT INTO currencies (`code`,`money_name`,`symbol`) VALUES('USD','United States Dollar','u$s');
INSERT INTO currencies (`code`,`money_name`) VALUES('UYU','Uruguay Peso');
INSERT INTO currencies (`code`,`money_name`) VALUES('UZS','Uzbekistan Som');
INSERT INTO currencies (`code`,`money_name`) VALUES('VEF','Venezuela Bolivar');
INSERT INTO currencies (`code`,`money_name`) VALUES('VND','Viet Nam Dong');
INSERT INTO currencies (`code`,`money_name`) VALUES('VUV','Vanuatu Vatu');
INSERT INTO currencies (`code`,`money_name`) VALUES('WST','Samoa Tala');
INSERT INTO currencies (`code`,`money_name`) VALUES('XAF','Communauté Financière Africaine (BEAC) CFA Franc BEAC');
INSERT INTO currencies (`code`,`money_name`) VALUES('XCD','East Caribbean Dollar');
INSERT INTO currencies (`code`,`money_name`) VALUES('XDR','International Monetary Fund (IMF) Special Drawing Rights');
INSERT INTO currencies (`code`,`money_name`) VALUES('XOF','Communauté Financière Africaine (BCEAO) Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('XPF','Comptoirs Français du Pacifique (CFP) Franc');
INSERT INTO currencies (`code`,`money_name`) VALUES('YER','Yemen Rial');
INSERT INTO currencies (`code`,`money_name`) VALUES('ZAR','South Africa Rand');
INSERT INTO currencies (`code`,`money_name`) VALUES('ZMW','Zambia Kwacha');
INSERT INTO currencies (`code`,`money_name`) VALUES('ZWD','Zimbabwe Dollar');
